name: ReSharper .NET Code Analysis

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write
  actions: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  resharper-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: resharper
        uses: JetBrains/ReSharper-InspectCode@main
        with:
          solution: Pure/BreakAway.sln
          format: text
          output: resharper-output.txt
          swea: true
      - name: Output report
        run: cat resharper-output.txt >> $GITHUB_STEP_SUMMARY
